version: "3"
services:
  db:
    container_name: patchman-db
    image: postgres:latest
    restart: always
    environment:
      - PGUSER=patchman
      - POSTGRES_USER=patchman
      - POSTGRES_PASSWORD=patchman
      - POSTGRES_DB=patchman
    volumes: 
      - ./db:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: 50m
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    image: patchman/custom
    container_name: patchman
    restart: always
    build:
        context: .
        dockerfile: docker/Dockerfile
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - /root/patchmanDocker/db:/var/lib/patchman/db
      # Add Host Trusted Certificates
      - "/usr/local/share/ca-certificates:/build/docker/certs/custom:ro"
      - ./input:/input
    ports:
      - "127.0.0.1:8856:8856"
    logging:
      driver: json-file
      options:
        max-size: 50m
    healthcheck:
     test: ["CMD", "wget","--output-document=-","--quiet","--tries=1","http://127.0.0.1:8856/patchman/"]
     interval: 10m
     timeout: 1m
     retries: 3
     start_period: 2m
    # Wait for Services to come up
    depends_on:
      db:
        condition: service_healthy    
    environment:
      # Enable Parsed Config Printing
      #- DOCKER_VERBOSE_CONFIG=True
      # Database
      - PATCHMAN_DB=POSTGRES
      # Use Containername as Host
      - POSTGRES_HOST=patchman-db
      - POSTGRES_USER=patchman
      - POSTGRES_PASSWORD=patchman
      - POSTGRES_DB=patchman
      # # Cache
      # - PATCHMAN_CACHE=REDIS
      # # Use Containername as Host
      # - REDISHOST=patchman-cache
      # - REDISAUTH=exampleRedisPassword
      # Configuration
      - TIME_ZONE=Europe/Berlin
      - BIND_ADDRESS=0.0.0.0:8856
      - PATCHMAN_SECRET_KEY=VERYSECRETFORDEVELOPMENTONLY
      - PATCHMAN_MAX_MIRRORS=5
      - PATCHMAN_DAYS_WITHOUT_REPORT=5
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
      - DEBUG=True
      - OFFLINE_MODE=False
      - CSRF_COOKIE_SECURE=False
      - SCRIPT_NAME=/patchman
