version: "3"
services:
  cache:
    container_name: patchman-cache
    image: redis:latest
    restart: always
    #ports:
    #  - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ./cache:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  db:
    container_name: patchman-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    #ports:
    #  - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    #image: powerdnsadmin/pda-legacy:latest
    image: patchman/custom
    container_name: patchman
    restart: always
    build:
        context: .
        dockerfile: docker/Dockerfile
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - /root/patchmanDocker/db:/var/lib/patchman/db
      # Add Host Trusted Certificates
      - "/usr/local/share/ca-certificates:/build/docker/certs/custom:ro"
      - ./input:/input
    network_mode: "host"
    logging:
      driver: json-file
      options:
        max-size: 50m
    #healthcheck:
    #  test: ["CMD", "patchman", "-a" ]
    #  interval: 10m
    #  timeout: 8m
    #  retries: 3
    #  start_period: 2m
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
      
    environment:
      - TIME_ZONE=Europe/Berlin
      - BIND_ADDRESS=127.0.0.1:8856
      - PATCHMAN_SECRET_KEY='VERYSECRETFORDEVELOPMENTONLY'
      - PATCHMAN_MAX_MIRRORS=5
      - PATCHMAN_DAYS_WITHOUT_REPORT=5
      - PATCHMAN_CACHE=MEMCACHE
      - PATCHMAN_DB=SQLLITE
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
      - DEBUG=True
      - OFFLINE_MODE=False
      - CSRF_COOKIE_SECURE=False
      - SCRIPT_NAME=/patchman
      - DOCKER_VERBOSE_CONFIG=True
